cgfie_inscriptions_homepage:
    pattern:  /
    defaults: { _controller: CgfieInscriptionsBundle:Default:index }
    requirements:
        _method:  GET    

cgfie_inscriptions_format06:
    pattern:  /admin/formato_acciones_formacion/
    defaults: { _controller: CgfieInscriptionsBundle:Default:format06 }

cgfie_inscriptions_course:
    pattern:  /accion_formacion/{id}
    defaults: { _controller: CgfieInscriptionsBundle:Default:courses, id: 0 }

cgfie_inscriptions_add:
    pattern:  admin/nuevo_formato
    defaults: { _controller: CgfieInscriptionsBundle:Default:addinscription}
