parameters:
    #gender: ['Masculino' ,'Femenino']

services:
    cgfie_inscriptions.admin.cgfie_users:
        class: Cgfie\InscriptionsBundle\Admin\CgfieUsersAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: CGFIE, label: "Usuarios CGFIE" }
        arguments:
            - ~	
            - Cgfie\InscriptionsBundle\Entity\CgfieUsers
            - 'SonataAdminBundle:CRUD'    
        calls:
            - [ setTranslationDomain, [CgfieInscriptionsBundle]]
