parameters:
    #gender: ['Masculino' ,'Femenino']

services:
    cgfie_inscriptions.admin.cgfie_users:
        class: Cgfie\InscriptionsBundle\Admin\CgfieUsersAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: CGFIE, label: "Usuarios CGFIE" }
        arguments:
            - ~	
            - Cgfie\InscriptionsBundle\Entity\CgfieUsers
            - 'SonataAdminBundle:CRUD'    
        calls:
            - [ setTranslationDomain, [CgfieInscriptionsBundle]]

    cgfie_inscriptions.admin.course:
        class: Cgfie\InscriptionsBundle\Admin\CourseAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: CGFIE, label: "Acciones de Formación" }
        arguments:
            - ~ 
            - Cgfie\InscriptionsBundle\Entity\Course
            - 'SonataAdminBundle:CRUD'    
        calls:
            - [ setTranslationDomain, [CgfieInscriptionsBundle]]

    cgfie_inscriptions.admin.cgfie_entity:
        class: Cgfie\InscriptionsBundle\Admin\CgfieEntityAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: CGFIE, label: "Unidades de Procedencia" }
        arguments:
            - ~ 
            - Cgfie\InscriptionsBundle\Entity\CgfieEntity
            - 'SonataAdminBundle:CRUD'    
        calls:
            - [ setTranslationDomain, [CgfieInscriptionsBundle]]

    cgfie_inscriptions.admin.training_area:
        class: Cgfie\InscriptionsBundle\Admin\TrainingAreaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: CGFIE, label: "Áreas de Formación" }
        arguments:
            - ~ 
            - Cgfie\InscriptionsBundle\Entity\TrainingArea
            - 'SonataAdminBundle:CRUD'    
        calls:
            - [ setTranslationDomain, [CgfieInscriptionsBundle]]

#    cgfie_inscriptions.admin.inscription:
#        class: Cgfie\InscriptionsBundle\Admin\InscriptionAdmin
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: CGFIE, label: "Formatos" }
#        arguments:
#            - ~ 
#            - Cgfie\InscriptionsBundle\Entity\Inscription
#            - 'SonataAdminBundle:CRUD'    
#        calls:
#            - [ setTranslationDomain, [CgfieInscriptionsBundle]]

#    cgfie_inscriptions.admin.inscription_users:
#        class: Cgfie\InscriptionsBundle\Admin\InscriptionUsersAdmin
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: CGFIE, label: "Formatos-Usuarios" }
#        arguments:
#            - ~ 
#            - Cgfie\InscriptionsBundle\Entity\InscriptionUsers
#            - 'SonataAdminBundle:CRUD'    
#        calls:
#            - [ setTranslationDomain, [CgfieInscriptionsBundle]]