parameters:
#    cgfie_inscriptions.example.class: Cgfie\InscriptionsBundle\Example

services:
#    cgfie_inscriptions.example:
#        class: %cgfie_inscriptions.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
