<?php

namespace Cgfie\InscriptionsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CgfieUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CgfieUsersRepository extends EntityRepository
{

}
