<?php

namespace Cgfie\InscriptionsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends EntityRepository
{
	protected $repository;

	public function __construct()
	{
		$this->repository =  $this->getDoctrine()->getRepository('CgfieInscriptionsBundle:Course');
	}

	public function getAllCourses()
	{		
		return $this->repository->findAll();
	}
}
