<?php

namespace Cgfie\InscriptionsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrainingAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainingAreaRepository extends EntityRepository
{
}
