parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     cgfie
    database_user:     root
    database_password: 

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            es
    secret:            219059b068b8b6cabc0a56747c06e5b0f8c606ab
